import { MainHeader } from "@/components/layout/header/main-header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className={inter.className}>
        <body>
          <div className="flex flex-col min-h-screen">
            <MainHeader />
            {children}
          </div>
        </body>
      </html>
    </Providers>
  );
}
